#-ed

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -242,228 +242,229 @@ jobs:
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0.7}
 
-  deploy-frontend:
-    docker:
-      - image: python:3.10-alpine3.16
-      #Docker image here that supports AWS CLI
-    steps:
-      - checkout
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update --no-cache tar
-            apk add --update --no-cache gzip
-            apk add --update --no-cache nodejs
-            apk add --update --no-cache npm
-            apk add --update --no-cache aws-cli
-            apk add --update --no-cache curl
-      - run:
-          name: Get backend url
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
-      - run:
-          name: Deploy frontend objects
-          command: |
-            cd frontend
-            npm install
-            npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+  # deploy-frontend:
+  #   docker:
+  #     - image: python:3.10-alpine3.16
+  #     #Docker image here that supports AWS CLI
+  #   steps:
+  #     - checkout
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           apk add --update --no-cache tar
+  #           apk add --update --no-cache gzip
+  #           apk add --update --no-cache nodejs
+  #           apk add --update --no-cache npm
+  #           apk add --update --no-cache aws-cli
+  #           apk add --update --no-cache curl
+  #     - run:
+  #         name: Get backend url
+  #         command: |
+  #           export BACKEND_IP=$(aws ec2 describe-instances \
+  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+  #             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+  #             --output text)
+  #           export API_URL="http://${BACKEND_IP}:3030"
+  #           echo "${API_URL}"
+  #           echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+  #           cat frontend/.env
+  #     - run:
+  #         name: Deploy frontend objects
+  #         command: |
+  #           cd frontend
+  #           npm install
+  #           npm run build
+  #           tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+  #           aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
             
-      # Here's where you will add some code to rollback on failure      
-      - destroy-environment:
-          circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
-      - revert-migrations: 
-          circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
+  #     # Here's where you will add some code to rollback on failure      
+  #     - destroy-environment:
+  #         circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
+  #     - revert-migrations: 
+  #         circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
                     
-  deploy-backend:
-    docker:
-      - image: python:3.10-alpine3.16
-    steps:
-      # Checkout code from git
-      - checkout
-      # Add ssh keys with fingerprint
-      - add_ssh_keys:
-         fingerprints:
-            - "8e:98:8c:e1:3b:70:33:69:f5:f7:4c:59:b2:fb:8b:b0"
-      # attach workspace
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update --no-cache ansible tar gzip nodejs npm curl aws-cli
-      - run:
-          name: Deploy backend
-          command: |
-            pwd
-            cd backend
+  # deploy-backend:
+  #     # Docker image that supports Ansible
+  #   docker:
+  #     - image: python:3.10-alpine3.16
+  #   steps:
+  #     # Checkout code from git
+  #     - checkout
+  #     # Add ssh keys with fingerprint
+  #     - add_ssh_keys:
+  #       fingerprints:
+  #           - "8e:98:8c:e1:3b:70:33:69:f5:f7:4c:59:b2:fb:8b:b0"
+  #     # attach workspace
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           apk add --update --no-cache ansible tar gzip nodejs npm curl aws-cli
+  #     - run:
+  #         name: Deploy backend
+  #         command: |
+  #           pwd
+  #           cd backend
             
-            touch .env
-            echo ENVIRONMENT=production > ".env"
-            echo TYPEORN_CONNECTION=postgress >> ".env"
-            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ".env"
-            echo TYPEORN_MIGRATIONS=./src/migrations/*.ts >> ".env"
-            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
-            echo NODE_ENV=production >> ".env"
-            echo TYPEORN_HOST=$TYPEORM_HOST >> ".env"
-            echo TYPEORM_PORT=$TYPEORN_PORT >> ".env"
-            echo TYPEORN_USERNANE=$TYPEORM_USERNAME >> ".env"
-            echo TYPEORN_PASSWORD=$TYPEORM_PASSWORD >> ".env"
-            echo TYPEORN_DATABASE=$TYPEORM_DATABASE >> ".env"
+  #           touch .env
+  #           echo ENVIRONMENT=production > ".env"
+  #           echo TYPEORN_CONNECTION=postgress >> ".env"
+  #           echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ".env"
+  #           echo TYPEORN_MIGRATIONS=./src/migrations/*.ts >> ".env"
+  #           echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
+  #           echo NODE_ENV=production >> ".env"
+  #           echo TYPEORN_HOST=$TYPEORM_HOST >> ".env"
+  #           echo TYPEORM_PORT=$TYPEORN_PORT >> ".env"
+  #           echo TYPEORN_USERNANE=$TYPEORM_USERNAME >> ".env"
+  #           echo TYPEORN_PASSWORD=$TYPEORM_PASSWORD >> ".env"
+  #           echo TYPEORN_DATABASE=$TYPEORM_DATABASE >> ".env"
             
             
-            pwd
-            ls -al
-            npm install
-            npm run build
-            cd ..
-            pwd
-            ls -al
-            # Zip the directory 
-            tar -C backend -czvf artifact.tar.gz .
+  #           pwd
+  #           ls -al
+  #           npm install
+  #           npm run build
+  #           cd ..
+  #           pwd
+  #           ls -al
+  #           # Zip the directory 
+  #           tar -C backend -czvf artifact.tar.gz .
             
-            cd .circleci/ansible
+  #           cd .circleci/ansible
             
-            echo "Contents of the inventory.txt file is ---------"
-            cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml
-    # Here's where you will add some code to rollback on failure  
-    - destroy-environment:
-        circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
-    - revert-migrations: 
-        circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"      
+  #           echo "Contents of the inventory.txt file is ---------"
+  #           cat inventory.txt
+  #           ansible-playbook -i inventory.txt deploy-backend.yml
+  #   # Here's where you will add some code to rollback on failure  
+  #   - destroy-environment:
+  #       circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
+  #   - revert-migrations: 
+  #       circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"      
         
-  smoke-test:
-    docker:
-       - image: python:3.10-alpine3.16
-    steps:
-      # Checkout code from git
-      - checkout
-      - run:
-          name: Install dependencies
-          command: 
-            apk add --update --no-cache tar gzip nodejs npm curl aws-cli
+  # smoke-test:
+  #   docker:
+  #     - image: python:3.10-alpine3.16
+  #   steps:
+  #     # Checkout code from git
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies
+  #         command: 
+  #           apk add --update --no-cache tar gzip nodejs npm curl aws-cli
             
-      - run:
-          name: Get backend url and Backend smoke test.
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances \
-            --query "Reservations[*].Instances[*].[PublicIpAddress]") \
-            --filters "Namw-tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --output text)
-            echo ${BACKEND_IP}
+  #     - run:
+  #         name: Get backend url and Backend smoke test.
+  #         command: |
+  #           export BACKEND_IP=$(aws ec2 describe-instances \
+  #           --query "Reservations[*].Instances[*].[PublicIpAddress]") \
+  #           --filters "Namw-tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+  #           --output text)
+  #           echo ${BACKEND_IP}
             
-            export BACKEND-$(echo $BACKEN_IP | grep -o '[^ ]*$')
+  #           export BACKEND-$(echo $BACKEN_IP | grep -o '[^ ]*$')
             
-            echo $BACKEND
-            export API_URL="http://${BACKEND}:3030"
-            echo "API_URL=${API_URL}"
+  #           echo $BACKEND
+  #           export API_URL="http://${BACKEND}:3030"
+  #           echo "API_URL=${API_URL}"
             
-            echo "Sleeping for 1 minute"
-            sleep 60
+  #           echo "Sleeping for 1 minute"
+  #           sleep 60
             
-            if curl -v "${API_URL}/api/status" | grep "ok"
-            then
-              return 0
-            else
-              return 1
-              fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
-            then
-                # Change this to 0 after the job fails
-              return 1
-            else
-              return 1
-            fi
-      #      Here's where you will add some code to rollback on failure  
-      - destroy-environment:
-          circle_workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
-      - revert-migrations: 
-          circle_workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
+  #           if curl -v "${API_URL}/api/status" | grep "ok"
+  #           then
+  #             return 0
+  #           else
+  #             return 1
+  #             fi
+  #     - run:
+  #         name: Frontend smoke test.
+  #         command: |
+  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/#/employees"            
+  #           echo ${URL} 
+  #           if curl -s ${URL} | grep "Welcome"
+  #           then
+  #               # Change this to 0 after the job fails
+  #             return 1
+  #           else
+  #             return 1
+  #           fi
+  #     #      Here's where you will add some code to rollback on failure  
+  #     - destroy-environment:
+  #         circle_workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
+  #     - revert-migrations: 
+  #         circle_workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
 
-  cloudfront-update:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            yum -y install tar gzip
-        - run:
-          name: Get old stack workflow id
-          command: |
-            export OldWorkflowID=$(aws cloudformation \
-              list-exports --query "Exports[?Name==\'WorkflowID\'].Value" \
-              --no-paginate --output text | grep -o '[^-]*$' )
-            echo $OldWorkflowID >> ~/project/OldWorkflowID.txt
-            cat ~/project/OldWorkflowID.txt
-        - persist_to_workspace:
-            root: ~/
-            paths:
-              - project/OldWorkflowID.txt
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/cloudfront.yml \
-              --stack-name InitialStack \
-              --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --tags project=udapeople
-            echo OldWorkflowID: $(cat ~/project/OldWorkflowID.txt)
-            echo CurrentWorkflowID: "${CIRCLE_WORKFLOW_ID:0:7}"
+  # cloudfront-update:
+  #   docker:
+  #     - image: amazon/aws-cli
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           yum -y install tar gzip
+  #       - run:
+  #         name: Get old stack workflow id
+  #         command: |
+  #           export OldWorkflowID=$(aws cloudformation \
+  #             list-exports --query "Exports[?Name==\'WorkflowID\'].Value" \
+  #             --no-paginate --output text | grep -o '[^-]*$' )
+  #           echo $OldWorkflowID >> ~/project/OldWorkflowID.txt
+  #           cat ~/project/OldWorkflowID.txt
+  #       - persist_to_workspace:
+  #           root: ~/
+  #           paths:
+  #             - project/OldWorkflowID.txt
+  #     - run:
+  #         name: Update cloudfront distribution
+  #         command: |
+  #           aws cloudformation deploy \
+  #             --template-file .circleci/files/cloudfront.yml \
+  #             --stack-name InitialStack \
+  #             --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
+  #             --tags project=udapeople
+  #           echo OldWorkflowID: $(cat ~/project/OldWorkflowID.txt)
+  #           echo CurrentWorkflowID: "${CIRCLE_WORKFLOW_ID:0:7}"
         
-      # Here's where you will add some code to rollback on failure  
+  #     # Here's where you will add some code to rollback on failure  
 
-cleanup:
-    docker:
-      - image: amazon/aws-cli
-      steps:
-        - checkout
-        - run:
-            name: Install dependencies
-            command: |
-              yum install tar gzip -y
-        - attach_workspace:
-            at: ~/
-      - run:
-          name: Get old stack workflow id
-          command: |
-            export STACKS=($(aws cloudformation list-stacks --query "StacksSummeries[*].StackName" \
-              --stack-status-filter   CREATE_COMPLETE --  no-paginate --output text))
-            echo Stack names: "$(STACKS[@])"
-            cat ~/project/OldWorkflowID.txt
-            export OldWorkflowID=$(cat ~/OldWorkflowID.txt)
-            echo OldWorkflowID: "$(OldWorkflowID)"
-      - run:
-          name: Remove old stacks and files
-          command: |
-            export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
-            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
-            then 
-              echo "Deleting old stack"
-              echo "s3://udapeople-${OldWorkflowID}"
-              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive || true
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" || true
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" ||
-            else
-              echo "Stack is the latest"
-              fi
+# cleanup:
+#     docker:
+#       - image: amazon/aws-cli
+#       steps:
+#         - checkout
+#         - run:
+#             name: Install dependencies
+#             command: |
+#               yum install tar gzip -y
+#         - attach_workspace:
+#             at: ~/
+#       - run:
+#           name: Get old stack workflow id
+#           command: |
+#             export STACKS=($(aws cloudformation list-stacks --query "StacksSummeries[*].StackName" \
+#               --stack-status-filter   CREATE_COMPLETE --  no-paginate --output text))
+#             echo Stack names: "$(STACKS[@])"
+#             cat ~/project/OldWorkflowID.txt
+#             export OldWorkflowID=$(cat ~/OldWorkflowID.txt)
+#             echo OldWorkflowID: "$(OldWorkflowID)"
+#       - run:
+#           name: Remove old stacks and files
+#           command: |
+#             export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+#             if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
+#             then 
+#               echo "Deleting old stack"
+#               echo "s3://udapeople-${OldWorkflowID}"
+#               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive || true
+#               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" || true
+#               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" ||
+#             else
+#               echo "Stack is the latest"
+#               fi
 workflows:
   default:
     jobs:
@@ -485,14 +486,14 @@ workflows:
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
