fixed yet?

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,26 +17,25 @@ commands:
             aws s3 rm s3://udapeople-<< parameters.circle_workflow_id >> --recursive
             aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.circle_workflow_id >>
             aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.circle_workflow_id >>
-
+      #      exit 1
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
       circle_workflow_id:
-        type: string
+        type: string     
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          when: on_fail
           command: |
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
-            if(( $SUCCESS==1 )); 
+            SUCCESS=$(curl --insecure  https://kvdb.io/UJQH2oq3A13kUagVDb5jDC/migration_<< parameters.circle_workflow_id >>)
+            # Logic for reverting the database state
+            if (( $SUCCESS == 1 ));
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-            fi
-            
+              cd ~/project/backend
+              npm install
+              npm run migration:revert
+            fi 
 jobs:
   build-frontend:
     docker:
@@ -235,7 +234,7 @@ jobs:
           command: |
              if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
               then
-                  curl https://kvdb.io/UJQH2oq3A13kUagVDb5jDC migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+                  curl https://kvdb.io/UJQH2oq3A13kUagVDb5jDC/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
               fi
             #exit 1
      # Here's where you will add some code to rollback on failure    
@@ -245,18 +244,20 @@ jobs:
   deploy-frontend:
     docker:
       - image: python:3.10-alpine3.16
+      #Docker image here that supports AWS CLI
     steps:
       - checkout
       - attach_workspace:
           at: ~/
-      - restore_cache:
-          keys: [frontend-build]
       - run:
           name: Install dependencies
           command: |
-            apk add --update tar gzip curl nodejs npm openssh-client git
-            pip install awscli
-            aws --version
+            apk add --update --no-cache tar
+            apk add --update --no-cache gzip
+            apk add --update --no-cache nodejs
+            apk add --update --no-cache npm
+            apk add --update --no-cache aws-cli
+            apk add --update --no-cache curl
       - run:
           name: Get backend url
           command: |
@@ -264,7 +265,6 @@ jobs:
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --output text)
-            
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
@@ -273,15 +273,16 @@ jobs:
           name: Deploy frontend objects
           command: |
             cd frontend
-            cat .env
             npm install
             npm run build
             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+            
+      # Here's where you will add some code to rollback on failure      
       - destroy-environment:
           circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
       - revert-migrations: 
-            circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+            circle_workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}" 
                     
   # deploy-backend:
   #     # Docker image that supports Ansible
